import { normalizeProduct } from "./csvImporter";

export const mockImportedProducts = [
  {
    id: "samsung-55-tv",
    name: "Samsung 55 Inch Smart TV",
    category: "TV",
    store: "Best Buy",
    storeLogo: "",
    price: "$599",
    oldPrice: "$899",
    discountPercent: "33",
    dealScore: "94",
    score: "Excellent Deal",
    badge: " Big Drop",
    rating: "4.8",
    isTrending: "true",
    expiresAt: "2026-05-22",
    source: "Best Buy Canada Feed",
    affiliateNetwork: "CJ Affiliate",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1",
    link: "https://www.bestbuy.ca/",
  },
  {
    id: "nike-running-shoes",
    name: "Nike Running Shoes",
    category: "Shoes",
    store: "Nike",
    storeLogo: "",
    price: "$89",
    oldPrice: "$149",
    discountPercent: "40",
    dealScore: "91",
    score: "Strong Deal",
    badge: " Hot Fashion Deal",
    rating: "4.6",
    isTrending: "true",
    expiresAt: "2026-05-19",
    source: "Nike Canada Feed",
    affiliateNetwork: "Awin",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    link: "https://www.nike.com/ca/",
  },
  {
    id: "office-chair",
    name: "Ergonomic Office Chair",
    category: "Office",
    store: "Staples",
    storeLogo: "",
    price: "$179",
    oldPrice: "$299",
    discountPercent: "40",
    dealScore: "89",
    score: "Great Value",
    badge: " Office Deal",
    rating: "4.5",
    isTrending: "false",
    expiresAt: "2026-05-24",
    source: "Staples Canada Feed",
    affiliateNetwork: "Impact",
    image: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8",
    link: "https://www.staples.ca/",
  },
];

export const importedDeals = mockImportedProducts.map(normalizeProduct);